    sources:
      - MontaguSlab.glyphs
    axisOrder:
      - opsz
      - wght
    # outputDir: "../../fonts"
    buildOTF: false
    familyName: Montagu Slab
    stat:
      - name: Optical size
        tag: opsz
        values:
        - name: 14pt
          value: 14
        - name: 144pt
          value: 144
      - name: Weight
        tag: wght
        values:
        - name: Thin
          value: 100
        - name: ExtraLight
          value: 200
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
    instances:
      MontaguSlab144pt-Thin.ttf:
      - familyName: Montagu Slab 144pt
        styleName: "Thin"
        coordinates:
          opsz: 144
          wght: 100
      # - styleName: "ExtraLight"
      #   coordinates:
      #     opsz: 144
      #     wght: 200
      # - styleName: "Regular"
      #   coordinates:
      #     opsz: 144
      #     wght: 400
      # - styleName: "Medium"
      #   coordinates:
      #     opsz: 144
      #     wght: 500
      # - styleName: "SemiBold"
      #   coordinates:
      #     opsz: 144
      #     wght: 600
      # - styleName: "Bold"
      #   coordinates:
      #     opsz: 144
      #     wght: 700